import Foundation
import SwiftUI

enum JournalItemStatus: String, Decodable, CaseIterable { case planned = "PLANNED", ready = "READY", inProgress = "IN_PROGRESS", blocked = "BLOCKED", deferred = "DEFERRED", done = "DONE", dropped = "DROPPED"
    var label: String { switch self { case .planned: "Planned"; case .ready: "Ready"; case .inProgress: "In progress"; case .blocked: "Blocked"; case .deferred: "Deferred"; case .done: "Done"; case .dropped: "Dropped" } }
    var icon: String { switch self { case .planned: "calendar"; case .ready: "checklist"; case .inProgress: "arrow.triangle.2.circlepath"; case .blocked: "exclamationmark.triangle"; case .deferred: "clock"; case .done: "checkmark.circle"; case .dropped: "archivebox" } }
    var isActive: Bool { [.planned, .ready, .inProgress, .blocked].contains(self) }
}
enum JournalEvidenceType: String, Decodable { case assumption = "ASSUMPTION", code = "CODE_VERIFIED", test = "TEST_VERIFIED", ci = "CI_VERIFIED", runtime = "RUNTIME_VERIFIED", provider = "PROVIDER_VERIFIED", deployment = "DEPLOYMENT_VERIFIED", user = "USER_REPORTED", physical = "PHYSICALLY_VERIFIED"
    var label: String { switch self { case .assumption: "Assumption"; case .code: "Code verified"; case .test: "Test verified"; case .ci: "CI verified"; case .runtime: "Runtime verified"; case .provider: "Provider verified"; case .deployment: "Deployment verified"; case .user: "User reported"; case .physical: "Physically verified" } }
}
enum JournalEvidenceResult: String, Decodable { case pass = "PASS", fail = "FAIL", partial = "PARTIAL", inconclusive = "INCONCLUSIVE" }

struct JournalProject: Decodable, Identifiable { let id: String; let projectKey: String; let displayName: String; let summary: String; let lifecycle: String; let createdAt: Date?; let updatedAt: Date?; enum CodingKeys: String, CodingKey { case id; case projectKey = "project_key"; case displayName = "display_name"; case summary; case lifecycle; case createdAt = "created_at"; case updatedAt = "updated_at" } }
struct JournalComponent: Decodable, Identifiable { let id: String; let projectId: String; let componentKey: String; let displayName: String; let parentId: String?; enum CodingKeys: String, CodingKey { case id; case projectId = "project_id"; case componentKey = "component_key"; case displayName = "display_name"; case parentId = "parent_id" } }
struct JournalItem: Decodable, Identifiable { let id: String; let projectId: String; let componentId: String?; let itemKey: String; let title: String; let summary: String; let status: JournalItemStatus; let priority: Int; let nextAction: String?; let version: Int; let createdAt: Date?; let updatedAt: Date?; enum CodingKeys: String, CodingKey { case id; case projectId = "project_id"; case componentId = "component_id"; case itemKey = "item_key"; case title; case summary; case status; case priority; case nextAction = "next_action"; case version; case createdAt = "created_at"; case updatedAt = "updated_at" } }
struct JournalEvent: Decodable, Identifiable { let id: String; let itemId: String; let eventType: String; let occurredAt: Date?; let recordedAt: Date?; let itemKey: String?; let itemTitle: String?; let componentId: String?; let componentName: String?; let summary: String?; let releaseId: String?; let releaseVersionLabel: String?; let releaseBuildLabel: String?; let result: String?; enum CodingKeys: String, CodingKey { case id; case itemId = "item_id"; case eventType = "event_type"; case occurredAt = "occurred_at"; case recordedAt = "recorded_at"; case itemKey = "item_key"; case itemTitle = "item_title"; case componentId = "component_id"; case componentName = "component_name"; case summary; case releaseId = "release_id"; case releaseVersionLabel = "release_version_label"; case releaseBuildLabel = "release_build_label"; case result } }
struct JournalEvidence: Decodable, Identifiable { let id: String; let itemId: String; let releaseId: String?; let claimKey: String; let claim: String; let evidenceType: JournalEvidenceType; let result: JournalEvidenceResult?; let observerActorId: String; let recordedByActorId: String; let observedAt: Date?; let state: String; let artifactReference: String?; enum CodingKeys: String, CodingKey { case id; case itemId = "item_id"; case releaseId = "release_id"; case claimKey = "claim_key"; case claim; case evidenceType = "evidence_type"; case result; case observerActorId = "observer_actor_id"; case recordedByActorId = "recorded_by_actor_id"; case observedAt = "observed_at"; case state; case artifactReference = "artifact_reference" } }
struct JournalLink: Decodable, Identifiable { let id: String; let projectId: String; let sourceItemId: String; let targetItemId: String; let relation: String; enum CodingKeys: String, CodingKey { case id; case projectId = "project_id"; case sourceItemId = "source_item_id"; case targetItemId = "target_item_id"; case relation } }
struct JournalDecision: Decodable, Identifiable { let id: String; let projectId: String; let componentId: String?; let itemId: String?; let decisionKey: String; let statement: String; let rationale: String; let state: String; let doNotRevisit: Bool; let revisitRequiresReason: String?; let supersedesId: String?; let effectiveFrom: Date?; let createdAt: Date?; let componentName: String?; enum CodingKeys: String, CodingKey { case id; case projectId = "project_id"; case componentId = "component_id"; case itemId = "item_id"; case decisionKey = "decision_key"; case statement; case rationale; case state; case doNotRevisit = "do_not_revisit"; case revisitRequiresReason = "revisit_requires_reason"; case supersedesId = "supersedes_id"; case effectiveFrom = "effective_from"; case createdAt = "created_at"; case componentName = "component_name" } }
struct JournalRelease: Decodable, Identifiable { let id: String; let projectId: String; let componentId: String?; let componentName: String?; let releaseKey: String; let versionLabel: String?; let buildLabel: String?; let channel: String?; let status: String; let releasedAt: Date?; let summary: String?; let createdAt: Date?; enum CodingKeys: String, CodingKey { case id; case projectId = "project_id"; case componentId = "component_id"; case componentName = "component_name"; case releaseKey = "release_key"; case versionLabel = "version_label"; case buildLabel = "build_label"; case channel; case status; case releasedAt = "released_at"; case summary; case createdAt = "created_at" } }
struct JournalVerification: Decodable, Identifiable { let id: String; let releaseId: String; let claimKey: String; let description: String; let requiredEvidenceType: JournalEvidenceType; let satisfaction: String; enum CodingKeys: String, CodingKey { case id; case releaseId = "release_id"; case claimKey = "claim_key"; case description; case requiredEvidenceType = "required_evidence_type"; case satisfaction } }
struct JournalOverview: Decodable { let project: JournalProject; let counts: [String: Int]; let recentActivity: [JournalEvent]; let latestRelease: JournalRelease?; let decisions: [JournalDecision]; enum CodingKeys: String, CodingKey { case project; case counts; case recentActivity = "recent_activity"; case latestRelease = "latest_release"; case decisions } }
struct JournalItemDetail: Decodable { let item: JournalItem; let events: [JournalEvent]; let evidence: [JournalEvidence]; let links: [JournalLink] }
struct JournalReleaseItem: Decodable, Identifiable { let itemId: String; let itemKey: String; let title: String; let status: JournalItemStatus; var id: String { itemId }; enum CodingKeys: String, CodingKey { case itemId = "item_id"; case itemKey = "item_key"; case title; case status } }
struct JournalReleaseDetail: Decodable { let release: JournalRelease; let items: [JournalReleaseItem]; let evidence: [JournalEvidence]; let verification: [JournalVerification] }
private struct JournalProjectsResponse: Decodable { let projects: [JournalProject] }
private struct JournalComponentsResponse: Decodable { let components: [JournalComponent] }
private struct JournalItemsResponse: Decodable { let items: [JournalItem] }
private struct JournalDecisionsResponse: Decodable { let decisions: [JournalDecision] }
private struct JournalTimelineResponse: Decodable { let timeline: [JournalEvent] }
private struct JournalReleasesResponse: Decodable { let releases: [JournalRelease] }

extension MainProductAPI {
    func journalProjects() async throws -> [JournalProject] { try await request(path: "/api/journal/projects", as: JournalProjectsResponse.self).projects }
    func journalComponents(projectId: String) async throws -> [JournalComponent] { try await request(path: "/api/journal/projects/\(projectId)/components", as: JournalComponentsResponse.self).components }
    func journalOverview(projectId: String) async throws -> JournalOverview { try await request(path: "/api/journal/projects/\(projectId)/overview", as: JournalOverview.self) }
    func journalItems(projectId: String, status: JournalItemStatus? = nil) async throws -> [JournalItem] { var path = "/api/journal/projects/\(projectId)/items?limit=100"; if let status { path += "&status=\(status.rawValue)" }; return try await request(path: path, as: JournalItemsResponse.self).items }
    func journalItem(id: String) async throws -> JournalItemDetail { try await request(path: "/api/journal/items/\(id)", as: JournalItemDetail.self) }
    func journalTimeline(projectId: String) async throws -> [JournalEvent] { try await request(path: "/api/journal/projects/\(projectId)/timeline?limit=100", as: JournalTimelineResponse.self).timeline }
    func journalDecisions(projectId: String) async throws -> [JournalDecision] { try await request(path: "/api/journal/projects/\(projectId)/decisions?limit=100", as: JournalDecisionsResponse.self).decisions }
    func journalReleases(projectId: String) async throws -> [JournalRelease] { try await request(path: "/api/journal/projects/\(projectId)/releases", as: JournalReleasesResponse.self).releases }
    func journalRelease(id: String) async throws -> JournalReleaseDetail { try await request(path: "/api/journal/releases/\(id)", as: JournalReleaseDetail.self) }
}

@MainActor final class ProjectJournalStore: ObservableObject {
    @Published var projects: [JournalProject] = []; @Published var selectedProject: JournalProject?; @Published var overview: JournalOverview?; @Published var items: [JournalItem] = []; @Published var timeline: [JournalEvent] = []; @Published var decisions: [JournalDecision] = []; @Published var releases: [JournalRelease] = []; @Published var isLoading = false; @Published var error: String?
    func load() async { isLoading = true; error = nil; do { projects = try await MainProductAPI.shared.journalProjects(); guard let project = projects.first else { selectedProject = nil; isLoading = false; return }; selectedProject = project; overview = try await MainProductAPI.shared.journalOverview(projectId: project.id); async let i = MainProductAPI.shared.journalItems(projectId: project.id); async let t = MainProductAPI.shared.journalTimeline(projectId: project.id); async let d = MainProductAPI.shared.journalDecisions(projectId: project.id); async let r = MainProductAPI.shared.journalReleases(projectId: project.id); items = try await i; timeline = try await t; decisions = try await d; releases = try await r } catch let requestError { self.error = (requestError as? LocalizedError)?.errorDescription ?? "Journal is temporarily unavailable." }; isLoading = false }
}

struct ProjectJournalView: View {
    @StateObject private var store = ProjectJournalStore()
    var body: some View { NavigationStack { Group { if store.isLoading && store.selectedProject == nil { ProgressView("Loading Project Journal…").frame(maxWidth: .infinity, minHeight: 180) } else if let project = store.selectedProject { List { Section { projectHeader(project) }; Section("Work") { NavigationLink { JournalWorkView(items: store.items) } label: { Label("Work", systemImage: "checklist"); Spacer(); Text("\(store.items.count)").foregroundStyle(.secondary) } }; Section("History") { NavigationLink { JournalTimelineView(events: store.timeline) } label: { Label("Timeline", systemImage: "clock.arrow.circlepath") }; NavigationLink { JournalDecisionsView(decisions: store.decisions) } label: { Label("Decisions", systemImage: "signpost.right") }; NavigationLink { JournalReleasesView(releases: store.releases) } label: { Label("Releases", systemImage: "shippingbox") } }; if let error = store.error { Text(error).foregroundStyle(.red) } } } else if store.projects.isEmpty && !store.isLoading { ContentUnavailableView("No Project Journal data", systemImage: "book.closed", description: Text(store.error ?? "No projects are available.")); Button("Retry") { Task { await store.load() } }.buttonStyle(.borderedProminent) } }.navigationTitle("Project Journal").navigationBarTitleDisplayMode(.inline).refreshable { await store.load() }.task { await store.load() } } }
    private func projectHeader(_ project: JournalProject) -> some View { VStack(alignment: .leading, spacing: 8) { Label(project.displayName, systemImage: "folder").font(.title3.weight(.semibold)); Text(project.summary).font(.subheadline).foregroundStyle(.secondary); if let overview = store.overview { HStack { stat("Active", overview.counts["IN_PROGRESS", default: 0] + overview.counts["READY", default: 0] + overview.counts["PLANNED", default: 0] + overview.counts["BLOCKED", default: 0]); stat("Blocked", overview.counts["BLOCKED", default: 0]); stat("Deferred", overview.counts["DEFERRED", default: 0]); stat("Done", overview.counts["DONE", default: 0]) }.font(.caption) } }.textSelection(.enabled) }
    private func stat(_ title: String, _ value: Int) -> some View { VStack(alignment: .leading) { Text(title).foregroundStyle(.secondary); Text("\(value)").font(.headline.monospacedDigit()) } }
}

struct JournalWorkView: View { let items: [JournalItem]; @State private var filter = "Active"; @State private var search = ""; var filtered: [JournalItem] { items.filter { item in let statusOK = filter == "All" || (filter == "Active" && item.status.isActive) || (filter == item.status.label); return statusOK && (search.isEmpty || item.title.localizedCaseInsensitiveContains(search) || item.summary.localizedCaseInsensitiveContains(search)) } }; var body: some View { List { Picker("Filter", selection: $filter) { ForEach(["Active","Done","Deferred","Dropped","All"], id: \.self) { Text($0).tag($0) } }.pickerStyle(.segmented).listRowBackground(Color.clear); if filtered.isEmpty { ContentUnavailableView("No matching work", systemImage: "checklist", description: Text("Try another filter.")) } else { ForEach(filtered) { item in NavigationLink { JournalItemDetailView(itemId: item.id, initial: item) } label: { JournalItemRow(item: item) } } } }.searchable(text: $search, prompt: "Search work").navigationTitle("Work").navigationBarTitleDisplayMode(.inline) } }
struct JournalItemRow: View { let item: JournalItem; var body: some View { HStack(alignment: .top, spacing: 10) { Image(systemName: item.status.icon).accessibilityLabel(item.status.label).foregroundStyle(item.status == .blocked ? .orange : .secondary); VStack(alignment: .leading, spacing: 4) { Text(item.title).font(.body.weight(.medium)); Text(item.status.label).font(.caption.weight(.semibold)); if !item.summary.isEmpty { Text(item.summary).font(.caption).foregroundStyle(.secondary).lineLimit(2) } } } } }
struct JournalItemDetailView: View { let itemId: String; let initial: JournalItem; @State private var detail: JournalItemDetail?; @State private var error: String?; var body: some View { List { Section { Text(initial.title).font(.title3.weight(.semibold)); Label(initial.status.label, systemImage: initial.status.icon); if !initial.summary.isEmpty { Text(initial.summary).textSelection(.enabled) } } ; if let detail { Section("Events") { ForEach(detail.events) { event in VStack(alignment: .leading) { Text(event.eventType.replacingOccurrences(of: "_", with: " ")).font(.subheadline.weight(.medium)); if let summary = event.summary { Text(summary).foregroundStyle(.secondary) }; if let date = event.occurredAt { Text(date.formatted(date: .abbreviated, time: .shortened)).font(.caption).foregroundStyle(.tertiary) } } } }; Section("Evidence") { if detail.evidence.isEmpty { Text("No evidence yet").foregroundStyle(.secondary) } else { ForEach(detail.evidence) { evidence in VStack(alignment: .leading, spacing: 4) { Text("\(evidence.evidenceType.label) · \(evidence.result?.rawValue ?? "—")").font(.subheadline.weight(.semibold)); Text(evidence.claim).textSelection(.enabled); if evidence.evidenceType == .physical { Text("Human physical observation").font(.caption).foregroundStyle(.secondary) } } } } } } else if let error { Text(error).foregroundStyle(.red) } }.navigationTitle("Item").navigationBarTitleDisplayMode(.inline).task { do { detail = try await MainProductAPI.shared.journalItem(id: itemId) } catch { self.error = "Item details are unavailable." } }.refreshable { do { detail = try await MainProductAPI.shared.journalItem(id: itemId) } catch { self.error = "Item details are unavailable." } } } }
struct JournalTimelineView: View { let events: [JournalEvent]; var body: some View { List { if events.isEmpty { ContentUnavailableView("No recent activity", systemImage: "clock") } else { ForEach(events) { event in VStack(alignment: .leading, spacing: 4) { Text(event.eventType.replacingOccurrences(of: "_", with: " ")).font(.subheadline.weight(.semibold)); if let summary = event.summary { Text(summary).foregroundStyle(.secondary).textSelection(.enabled) }; if let itemTitle = event.itemTitle { Text(itemTitle).font(.caption.weight(.medium)) }; if let componentName = event.componentName { Text(componentName).font(.caption).foregroundStyle(.secondary) }; if let version = event.releaseVersionLabel { Text("Release \(version)\(event.releaseBuildLabel.map { " · \($0)" } ?? "")").font(.caption2).foregroundStyle(.tertiary).textSelection(.enabled) }; if let date = event.occurredAt { Text(date.formatted(date: .abbreviated, time: .shortened)).font(.caption).foregroundStyle(.tertiary) } } } } }.navigationTitle("Timeline").navigationBarTitleDisplayMode(.inline) } }
struct JournalDecisionsView: View { let decisions: [JournalDecision]; var body: some View { List { if decisions.isEmpty { ContentUnavailableView("No decisions yet", systemImage: "signpost.right") } else { ForEach(decisions) { decision in NavigationLink { JournalDecisionDetailView(decision: decision) } label: { VStack(alignment: .leading, spacing: 4) { Text(decision.statement).lineLimit(3); Text(decision.state + (decision.doNotRevisit ? " · Do not revisit" : "")).font(.caption).foregroundStyle(.secondary) } } } } }.navigationTitle("Decisions").navigationBarTitleDisplayMode(.inline) } }
struct JournalDecisionDetailView: View { let decision: JournalDecision; var body: some View { List { Section { Text(decision.statement).font(.headline).textSelection(.enabled); Text(decision.state).font(.subheadline) } ; Section("Rationale") { Text(decision.rationale.isEmpty ? "No rationale recorded." : decision.rationale).textSelection(.enabled) }; if decision.doNotRevisit { Section("Revisit rule") { Text(decision.revisitRequiresReason ?? "Requires explicit new reason.") } } }.navigationTitle("Decision").navigationBarTitleDisplayMode(.inline) } }
struct JournalReleasesView: View { let releases: [JournalRelease]; var body: some View { List { if releases.isEmpty { ContentUnavailableView("No releases yet", systemImage: "shippingbox") } else { ForEach(releases) { release in NavigationLink { JournalReleaseDetailView(releaseId: release.id, initial: release) } label: { VStack(alignment: .leading) { Text(release.versionLabel ?? release.releaseKey).font(.body.weight(.medium)); if let componentName = release.componentName { Text(componentName).font(.caption.weight(.medium)) }; Text([release.buildLabel, release.status].compactMap { $0 }.joined(separator: " · ")).font(.caption).foregroundStyle(.secondary) } } } } }.navigationTitle("Releases").navigationBarTitleDisplayMode(.inline) } }
struct JournalReleaseDetailView: View { let releaseId: String; let initial: JournalRelease; @State private var detail: JournalReleaseDetail?; @State private var error: String?; var body: some View { List { Section { Text(initial.versionLabel ?? initial.releaseKey).font(.title3.weight(.semibold)).textSelection(.enabled); if let componentName = initial.componentName { Text(componentName).font(.subheadline.weight(.medium)) }; Text(initial.buildLabel ?? "Build unavailable").textSelection(.enabled); Text(initial.status) }; if let detail { Section("Verification") { if detail.verification.isEmpty { Text("No verification requirements.").foregroundStyle(.secondary) } else { ForEach(detail.verification) { req in Label { VStack(alignment: .leading) { Text(req.claimKey); Text("Required: \(req.requiredEvidenceType.label) · \(req.satisfaction)").font(.caption).foregroundStyle(req.satisfaction == "SATISFIED" ? .green : .orange) } } icon: { Image(systemName: req.satisfaction == "SATISFIED" ? "checkmark.circle" : "exclamationmark.triangle") } } } }; Section("Evidence") { ForEach(detail.evidence) { e in Text("\(e.evidenceType.label) · \(e.result?.rawValue ?? "—")\n\(e.claim)").textSelection(.enabled) } } } else if let error { Text(error).foregroundStyle(.red) } }.navigationTitle("Release").navigationBarTitleDisplayMode(.inline).task { await load() }.refreshable { await load() } } ; private func load() async { do { detail = try await MainProductAPI.shared.journalRelease(id: releaseId); error = nil } catch { self.error = "Release details are unavailable." } } }
